# -*- coding: utf-8 -*-
import sympy
# Form implementation generated from reading ui file 'inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 479)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ###########
        self.label_privet = QtWidgets.QLabel(self.centralwidget)
        self.label_privet.setGeometry(QtCore.QRect(210, -20, 501, 181))
        self.label_privet.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_privet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_privet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_privet.setObjectName("label_help")
        ##########3
        self.label_help = QtWidgets.QLabel(self.centralwidget)
        self.label_help.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_help.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(0, 85, 0);\n"
                                        "font: 10pt \"Calisto MT\";")
        self.label_help.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_help.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_help.setObjectName("label_help")
        ###########
        self.pushButton_2spos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2spos.setGeometry(QtCore.QRect(450, 220, 330, 171))
        self.pushButton_2spos.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2spos.setObjectName("pushButton_2spos")
        self.pushButton_1spos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1spos.setGeometry(QtCore.QRect(10, 220, 371, 171))
        self.pushButton_1spos.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_1spos.setObjectName("pushButton_1spos")
        self.plainTextEdit_kroc = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_kroc.setGeometry(QtCore.QRect(10, 120, 281, 51))
        self.plainTextEdit_kroc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_kroc.setObjectName("plainTextEdit_kroc")
        self.label_kroc = QtWidgets.QLabel(self.centralwidget)
        self.label_kroc.setGeometry(QtCore.QRect(10, 0, 281, 101))
        self.label_kroc.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_kroc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_kroc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_kroc.setObjectName("label_kroc")
        self.label_znachx = QtWidgets.QLabel(self.centralwidget)
        self.label_znachx.setGeometry(QtCore.QRect(10, 220, 281, 101))
        self.label_znachx.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_znachx.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_znachx.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_znachx.setObjectName("label_znachx")
        self.label_znacfun1 = QtWidgets.QLabel(self.centralwidget)
        self.label_znacfun1.setGeometry(QtCore.QRect(390, 110, 191, 61))
        self.label_znacfun1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_znacfun1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_znacfun1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_znacfun1.setObjectName("label_znacfun1")
        self.label_znachfun2 = QtWidgets.QLabel(self.centralwidget)
        self.label_znachfun2.setGeometry(QtCore.QRect(390, 200, 191, 61))
        self.label_znachfun2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_znachfun2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_znachfun2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_znachfun2.setObjectName("label_znachfun2")
        self.label_znachfun3 = QtWidgets.QLabel(self.centralwidget)
        self.label_znachfun3.setGeometry(QtCore.QRect(390, 280, 191, 61))
        self.label_znachfun3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_znachfun3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_znachfun3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_znachfun3.setObjectName("label_znachfun3")
        self.label_znachfun = QtWidgets.QLabel(self.centralwidget)
        self.label_znachfun.setGeometry(QtCore.QRect(390, 0, 281, 101))
        self.label_znachfun.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_znachfun.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_znachfun.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_znachfun.setObjectName("label_znachfun")
        self.plainTextEdit_znach = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_znach.setGeometry(QtCore.QRect(10, 330, 281, 51))
        self.plainTextEdit_znach.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_znach.setObjectName("plainTextEdit_znach")
        self.plainTextEdit_znachfun1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_znachfun1.setGeometry(QtCore.QRect(600, 120, 171, 51))
        self.plainTextEdit_znachfun1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_znachfun1.setObjectName("plainTextEdit_znachfun1")
        self.plainTextEdit_znachfun2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_znachfun2.setGeometry(QtCore.QRect(600, 210, 171, 51))
        self.plainTextEdit_znachfun2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_znachfun2.setObjectName("plainTextEdit_znachfun2")
        self.plainTextEdit_znachfun3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_znachfun3.setGeometry(QtCore.QRect(600, 290, 171, 51))
        self.plainTextEdit_znachfun3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_znachfun3.setObjectName("plainTextEdit_znachfun3")
        self.pushButton_obchisliti1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_obchisliti1.setGeometry(QtCore.QRect(580, 350, 211, 71))
        self.pushButton_obchisliti1.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_obchisliti1.setObjectName("pushButton_obchisliti1")
        self.label_znachx_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_znachx_2.setGeometry(QtCore.QRect(440, 0, 341, 201))
        self.label_znachx_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_znachx_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_znachx_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_znachx_2.setObjectName("label_znachx_2")
        self.plainTextEdit_znach_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_znach_2.setGeometry(QtCore.QRect(440, 240, 341, 51))
        self.plainTextEdit_znach_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.plainTextEdit_znach_2.setObjectName("plainTextEdit_znach_2")
        self.pushButton_obchisliti1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_obchisliti1_2.setGeometry(QtCore.QRect(70, 320, 701, 101))
        self.pushButton_obchisliti1_2.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_obchisliti1_2.setObjectName("pushButton_obchisliti1_2")
####################
        self.pushButton_obchisliti1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_obchisliti1_3.setGeometry(QtCore.QRect(320,180 ,51, 121))
        self.pushButton_obchisliti1_3.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_obchisliti1_3.setObjectName("pushButton_obchisliti1_3")
#####################
        self.label_kroc_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_kroc_3.setGeometry(QtCore.QRect(70, 0, 281, 101))
        self.label_kroc_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_kroc_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_kroc_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_kroc_3.setObjectName("label_kroc_3")
        self.label_kroc_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_kroc_4.setGeometry(QtCore.QRect(70, 110, 281, 51))
        self.label_kroc_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_kroc_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_kroc_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_kroc_4.setObjectName("label_kroc_4")
        self.pushButton_cal1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal1.setGeometry(QtCore.QRect(70, 180, 51, 31))
        self.pushButton_cal1.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal1.setObjectName("pushButton_cal1")
        self.pushButton_cal2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal2.setGeometry(QtCore.QRect(120, 180, 51, 31))
        self.pushButton_cal2.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal2.setObjectName("pushButton_cal2")
        self.pushButton_cal3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal3.setGeometry(QtCore.QRect(170, 180, 51, 31))
        self.pushButton_cal3.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal3.setObjectName("pushButton_cal3")
        self.pushButton_cal4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal4.setGeometry(QtCore.QRect(220, 180, 51, 31))
        self.pushButton_cal4.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal4.setObjectName("pushButton_cal4")
        self.pushButton_cal5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal5.setGeometry(QtCore.QRect(270, 180, 51, 31))
        self.pushButton_cal5.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal5.setObjectName("pushButton_cal5")
        self.pushButton_cal9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal9.setGeometry(QtCore.QRect(170, 210, 51, 31))
        self.pushButton_cal9.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal9.setObjectName("pushButton_cal9")
        self.pushButton_cal11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal11.setGeometry(QtCore.QRect(270, 210, 51, 31))
        self.pushButton_cal11.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal11.setObjectName("pushButton_cal11")
        self.pushButton_cal8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal8.setGeometry(QtCore.QRect(120, 210, 51, 31))
        self.pushButton_cal8.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal8.setObjectName("pushButton_cal8")
        self.pushButton_cal7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal7.setGeometry(QtCore.QRect(70, 210, 51, 31))
        self.pushButton_cal7.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal7.setObjectName("pushButton_cal7")
        self.pushButton_cal10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal10.setGeometry(QtCore.QRect(220, 210, 51, 31))
        self.pushButton_cal10.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal10.setObjectName("pushButton_cal10")
        self.pushButton_cal15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal15.setGeometry(QtCore.QRect(170, 240, 51, 31))
        self.pushButton_cal15.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal15.setObjectName("pushButton_cal15")
        self.pushButton_cal17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal17.setGeometry(QtCore.QRect(270, 240, 51, 31))
        self.pushButton_cal17.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal17.setObjectName("pushButton_cal17")
        self.pushButton_cal14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal14.setGeometry(QtCore.QRect(120, 240, 51, 31))
        self.pushButton_cal14.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal14.setObjectName("pushButton_cal14")
        self.pushButton_cal13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal13.setGeometry(QtCore.QRect(70, 240, 51, 31))
        self.pushButton_cal13.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal13.setObjectName("pushButton_cal13")
        self.pushButton_cal16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal16.setGeometry(QtCore.QRect(220, 240, 51, 31))
        self.pushButton_cal16.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal16.setObjectName("pushButton_cal16")
        self.pushButton_cal23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal23.setGeometry(QtCore.QRect(270, 270, 51, 31))
        self.pushButton_cal23.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal23.setObjectName("pushButton_cal23")
        self.pushButton_cal20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal20.setGeometry(QtCore.QRect(120, 270, 51, 31))
        self.pushButton_cal20.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal20.setObjectName("pushButton_cal20")
        self.pushButton_cal21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal21.setGeometry(QtCore.QRect(170, 270, 51, 31))
        self.pushButton_cal21.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal21.setObjectName("pushButton_cal21")
        self.pushButton_cal22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal22.setGeometry(QtCore.QRect(220, 270, 51, 31))
        self.pushButton_cal22.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal22.setObjectName("pushButton_cal22")
        self.pushButton_cal19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cal19.setGeometry(QtCore.QRect(70, 270, 51, 31))
        self.pushButton_cal19.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_cal19.setObjectName("pushButton_cal19")
        self.label_resulttext = QtWidgets.QLabel(self.centralwidget)
        self.label_resulttext.setGeometry(QtCore.QRect(200, 10, 401, 121))
        self.label_resulttext.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_resulttext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_resulttext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_resulttext.setObjectName("label_resulttext")
        self.label_resultvivid = QtWidgets.QLabel(self.centralwidget)
        self.label_resultvivid.setGeometry(QtCore.QRect(210, 170, 401, 71))
        self.label_resultvivid.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Calisto MT\";")
        self.label_resultvivid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_resultvivid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_resultvivid.setObjectName("label_resultvivid")
        self.pushButton_povtor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_povtor.setGeometry(QtCore.QRect(60, 310, 241, 91))
        self.pushButton_povtor.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_povtor.setObjectName("pushButton_povtor")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(480, 310, 241, 91))
        self.pushButton_exit.setStyleSheet("background-color: rgb(119, 206, 79);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_1spos.raise_()
        self.pushButton_obchisliti1_3.raise_()
        self.label_privet.raise_()
        self.label_help.raise_()
        self.pushButton_2spos.raise_()
        self.plainTextEdit_kroc.raise_()
        self.label_kroc.raise_()
        self.label_znachx.raise_()
        self.label_znacfun1.raise_()
        self.label_znachfun2.raise_()
        self.label_znachfun3.raise_()
        self.label_znachfun.raise_()
        self.plainTextEdit_znach.raise_()
        self.plainTextEdit_znachfun1.raise_()
        self.plainTextEdit_znachfun2.raise_()
        self.plainTextEdit_znachfun3.raise_()
        self.pushButton_obchisliti1.raise_()
        self.label_znachx_2.raise_()
        self.plainTextEdit_znach_2.raise_()
        self.pushButton_obchisliti1_2.raise_()
        self.label_kroc_3.raise_()
        self.label_kroc_4.raise_()
        self.pushButton_cal1.raise_()
        self.pushButton_cal2.raise_()
        self.pushButton_cal3.raise_()
        self.pushButton_cal4.raise_()
        self.pushButton_cal5.raise_()
        self.pushButton_cal9.raise_()
        self.pushButton_cal11.raise_()
        self.pushButton_cal8.raise_()
        self.pushButton_cal7.raise_()
        self.pushButton_cal10.raise_()
        self.pushButton_cal15.raise_()
        self.pushButton_cal17.raise_()
        self.pushButton_cal14.raise_()
        self.pushButton_cal13.raise_()
        self.pushButton_cal16.raise_()
        self.pushButton_cal23.raise_()
        self.pushButton_cal20.raise_()
        self.pushButton_cal21.raise_()
        self.pushButton_cal22.raise_()
        self.pushButton_cal19.raise_()
        self.label_resulttext.raise_()
        self.label_resultvivid.raise_()
        self.pushButton_povtor.raise_()
        self.pushButton_exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_privet.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Привіт! Ця програми створена для </p><p align=\"center\">диференціювання функції (обчислення другої </p><p align=\"center\">похідної функції в точці ).Відповідно до наявних у вас </p><p align=\"center\">даних оберіть спосіб обчислення</p></body></html>"))
        self.pushButton_2spos.setText(_translate("MainWindow", "Вам відома функція \n"
                                                 "обчислюється за допомогою взяття \n"
                                                 "похідної від похідної"))
        self.pushButton_1spos.setText(_translate("MainWindow", "Вам відомі значення f(x) (використовується,\n"
"якщо функція задана таблично (обчислюється\n"
"за формулою похідної другого порядку)"))
        self.label_kroc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введіть крок </p><p align=\"center\">диференціювання h</p></body></html>"))
        self.label_znachx.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введіть x (точку у якій необхідно </p><p align=\"center\">знайти другу похідну)</p></body></html>"))
        self.label_znacfun1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">f(x-h) =</p></body></html>"))
        self.label_znachfun2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">f(x) =</p></body></html>"))
        self.label_znachfun3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">f(x+h) =</p></body></html>"))
        self.label_znachfun.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введіть значення функції</p><p align=\"center\"> у відповідних точках</p></body></html>"))
        self.pushButton_obchisliti1.setText(_translate("MainWindow", "Обчислити"))
        self.pushButton_obchisliti1_3.setText(_translate("MainWindow", "x"))
        self.label_znachx_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введіть x (точку у якій необхідно </p><p align=\"center\">знайти другу похідну)</p></body></html>"))
        self.pushButton_obchisliti1_2.setText(_translate("MainWindow", "Обчислити"))
        self.label_kroc_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введіть функцію</p><p align=\"center\">(за допомогою цифрової панелі)</p></body></html>"))
        self.label_kroc_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"> </p></body></html>"))
        self.pushButton_cal1.setText(_translate("MainWindow", "1"))
        self.label_help.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"> </p></body></html>"))
        self.pushButton_cal2.setText(_translate("MainWindow", "2"))
        self.pushButton_cal3.setText(_translate("MainWindow", "3"))
        self.pushButton_cal4.setText(_translate("MainWindow", "("))
        self.pushButton_cal5.setText(_translate("MainWindow", "cos"))
        self.pushButton_cal9.setText(_translate("MainWindow", "6"))
        self.pushButton_cal11.setText(_translate("MainWindow", "sin"))
        self.pushButton_cal8.setText(_translate("MainWindow", "5"))
        self.pushButton_cal7.setText(_translate("MainWindow", "4"))
        self.pushButton_cal10.setText(_translate("MainWindow", ")"))
        self.pushButton_cal15.setText(_translate("MainWindow", "9"))
        self.pushButton_cal17.setText(_translate("MainWindow", "**"))
        self.pushButton_cal14.setText(_translate("MainWindow", "8"))
        self.pushButton_cal13.setText(_translate("MainWindow", "7"))
        self.pushButton_cal16.setText(_translate("MainWindow", "-"))
        self.pushButton_cal23.setText(_translate("MainWindow", "del"))
        self.pushButton_cal20.setText(_translate("MainWindow", "0"))
        self.pushButton_cal21.setText(_translate("MainWindow", "/"))
        self.pushButton_cal22.setText(_translate("MainWindow", "+"))
        self.pushButton_cal19.setText(_translate("MainWindow", "*"))
        self.label_resulttext.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ваш результат</p></body></html>"))
        self.label_resultvivid.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ваш результат</p></body></html>"))
        self.pushButton_povtor.setText(_translate("MainWindow", "Повторити "))
        self.pushButton_exit.setText(_translate("MainWindow", "Вийти"))
        self.pushButton_exit.setVisible(False)
        self.label_resultvivid.setVisible(False)
        self.pushButton_povtor.setVisible(False)
        self.label_resulttext.setVisible(False)
        self.pushButton_obchisliti1_3.setVisible(False)
        self.pushButton_cal19.setVisible(False)
        self.pushButton_cal23.setVisible(False)
        self.pushButton_cal22.setVisible(False)
        self.pushButton_cal21.setVisible(False)
        self.pushButton_cal20.setVisible(False)
        self.pushButton_cal17.setVisible(False)
        self.pushButton_cal16.setVisible(False)
        self.pushButton_cal15.setVisible(False)
        self.pushButton_cal14.setVisible(False)
        self.pushButton_cal13.setVisible(False)
        self.pushButton_cal11.setVisible(False)
        self.pushButton_cal10.setVisible(False)
        self.pushButton_cal9.setVisible(False)
        self.pushButton_cal8.setVisible(False)
        self.pushButton_cal7.setVisible(False)
        self.pushButton_cal5.setVisible(False)
        self.pushButton_cal4.setVisible(False)
        self.pushButton_cal3.setVisible(False)
        self.pushButton_cal2.setVisible(False)
        self.pushButton_cal1.setVisible(False)
        self.label_kroc.setVisible(False)
        self.label_znachx.setVisible(False)
        self.label_znacfun1.setVisible(False)
        self.label_znachfun2.setVisible(False)
        self.label_znachfun3.setVisible(False)
        self.label_znachfun.setVisible(False)
        self.pushButton_obchisliti1.setVisible(False)
        self.label_znachx_2.setVisible(False)
        self.pushButton_obchisliti1_2.setVisible(False)
        self.label_kroc_3.setVisible(False)
        self.label_kroc_4.setVisible(False)
        self.plainTextEdit_kroc.setVisible(False)
        self.plainTextEdit_znach.setVisible(False)
        self.plainTextEdit_znachfun1.setVisible(False)
        self.plainTextEdit_znachfun2.setVisible(False)
        self.plainTextEdit_znachfun3.setVisible(False)
        self.plainTextEdit_znach_2.setVisible(False)
        self.pushButton_2spos.clicked.connect(self.spos2)
        self.pushButton_1spos.clicked.connect(self.spos1)
        self.pushButton_obchisliti1.clicked.connect(self.obchisliti1)
        self.pushButton_obchisliti1_2.clicked.connect(self.obchisliti1_2)
        self.pushButton_exit.clicked.connect(self.ex)
        self.pushButton_povtor.clicked.connect(self.povtor)
        self.pushButton_cal19.clicked.connect(lambda: self.panel(self.pushButton_cal19.text(),"*"))
        self.pushButton_cal22.clicked.connect(lambda: self.panel(self.pushButton_cal22.text(),"+"))
        self.pushButton_cal21.clicked.connect(lambda: self.panel(self.pushButton_cal21.text(),"/"))
        self.pushButton_cal20.clicked.connect(lambda: self.panel(self.pushButton_cal20.text(),"0"))
        self.pushButton_cal17.clicked.connect(lambda: self.panel(self.pushButton_cal17.text(),"**"))
        self.pushButton_cal16.clicked.connect(lambda: self.panel(self.pushButton_cal16.text(),"-"))
        self.pushButton_cal15.clicked.connect(lambda: self.panel(self.pushButton_cal15.text(),"9"))
        self.pushButton_cal14.clicked.connect(lambda: self.panel(self.pushButton_cal14.text(),"8"))
        self.pushButton_cal13.clicked.connect(lambda: self.panel(self.pushButton_cal13.text(),"7"))
        self.pushButton_cal11.clicked.connect(lambda: self.panel(self.pushButton_cal11.text(),"sin"))
        self.pushButton_cal10.clicked.connect(lambda: self.panel(self.pushButton_cal10.text(),")"))
        self.pushButton_cal9.clicked.connect(lambda: self.panel(self.pushButton_cal9.text(),"6"))
        self.pushButton_cal8.clicked.connect(lambda: self.panel(self.pushButton_cal8.text(),"5"))
        self.pushButton_cal7.clicked.connect(lambda: self.panel(self.pushButton_cal7.text(),"4"))
        self.pushButton_cal5.clicked.connect(lambda: self.panel(self.pushButton_cal5.text(),"cos"))
        self.pushButton_cal4.clicked.connect(lambda: self.panel(self.pushButton_cal4.text(),"("))
        self.pushButton_cal3.clicked.connect(lambda: self.panel(self.pushButton_cal3.text(),"3"))
        self.pushButton_cal2.clicked.connect(lambda: self.panel(self.pushButton_cal2.text(),"2"))
        self.pushButton_cal1.clicked.connect(lambda: self.panel(self.pushButton_cal1.text(),"1"))
        self.pushButton_obchisliti1_3.clicked.connect(lambda: self.panel(self.pushButton_obchisliti1_3.text(),"x"))
        self.pushButton_cal23.clicked.connect(self.deleteznach)

    def deleteznach(self):
            doc = QtGui.QTextDocument()
            doc.setHtml(self.label_kroc_4.text())
            text = doc.toPlainText()
            if text=="":
                    return
            elif text[-1]=="*" and text[-2]=="*" :
                    res=text[:-2]
                    self.label_kroc_4.setText(res)
            elif text[-1] == "s" and text[-2] == "o" and text[-3] == "c":
                    res = text[:-3]
                    self.label_kroc_4.setText(res)
            elif text[-1] == "n" and text[-2] == "i" and text[-3] == "s":
                    res = text[:-3]
                    self.label_kroc_4.setText(res)
            else:
                    res = text[:-1]
                    self.label_kroc_4.setText(res)


    def panel(self,znach,e):
        if self.label_kroc_4.text()=="":
                self.label_kroc_4.setText(znach)
                self.label_help.setText(e)

        else:
                self.label_kroc_4.setText(self.label_kroc_4.text() + znach)
                self.label_help.setText(self.label_help.text() + e)


    def spos2 (self):
            self.pushButton_cal19.setVisible(True)
            self.pushButton_cal23.setVisible(True)
            self.pushButton_cal22.setVisible(True)
            self.pushButton_cal21.setVisible(True)
            self.pushButton_cal20.setVisible(True)
            self.pushButton_cal17.setVisible(True)
            self.pushButton_cal16.setVisible(True)
            self.pushButton_cal15.setVisible(True)
            self.pushButton_cal14.setVisible(True)
            self.pushButton_cal13.setVisible(True)
            self.pushButton_obchisliti1_3.setVisible(True)
            self.pushButton_cal11.setVisible(True)
            self.pushButton_cal10.setVisible(True)
            self.pushButton_cal9.setVisible(True)
            self.pushButton_cal8.setVisible(True)
            self.pushButton_cal7.setVisible(True)
            self.pushButton_cal5.setVisible(True)
            self.pushButton_cal4.setVisible(True)
            self.pushButton_cal3.setVisible(True)
            self.pushButton_cal2.setVisible(True)
            self.pushButton_cal1.setVisible(True)
            self.label_znachx_2.setVisible(True)
            self.plainTextEdit_znach_2.setVisible(True)
            self.label_kroc_3.setVisible(True)
            self.label_kroc_4.setVisible(True)
            self.pushButton_obchisliti1_2.setVisible(True)
            self.pushButton_2spos.setVisible(False)
            self.label_privet.setVisible(False)
            self.pushButton_1spos.setVisible(False)


    def spos1(self):
            self.pushButton_2spos.setVisible(False)
            self.label_privet.setVisible(False)
            self.pushButton_1spos.setVisible(False)
            self.label_kroc.setVisible(True)
            self.label_znachx.setVisible(True)
            self.label_znacfun1.setVisible(True)
            self.label_znachfun2.setVisible(True)
            self.label_znachfun3.setVisible(True)
            self.label_znachfun.setVisible(True)
            self.pushButton_obchisliti1.setVisible(True)
            self.plainTextEdit_kroc.setVisible(True)
            self.plainTextEdit_znachfun1.setVisible(True)
            self.plainTextEdit_znachfun2.setVisible(True)
            self.plainTextEdit_znachfun3.setVisible(True)
            self.plainTextEdit_znach.setVisible(True)

    def obchisliti1(self):
            try:
                    kroc = float(self.plainTextEdit_kroc.toPlainText())
                    znach = float(self.plainTextEdit_znach.toPlainText())
                    znachfun1 = float(self.plainTextEdit_znachfun1.toPlainText())
                    znachfun2 = float(self.plainTextEdit_znachfun2.toPlainText())
                    znachfun3 = float(self.plainTextEdit_znachfun3.toPlainText())
                    res = ((znachfun3 - 2 * znachfun2 + znachfun1) / (kroc * kroc))
            except ValueError:
                    self.plainTextEdit_kroc.clear()
                    self.plainTextEdit_znach.clear()
                    self.plainTextEdit_znachfun1.clear()
                    self.plainTextEdit_znachfun2.clear()
                    self.plainTextEdit_znachfun3.clear()
                    error=QMessageBox()
                    error.setWindowTitle("Помилка")
                    error.setText("Ви ввели дані некоректно,значення мають бути дійсними числами")
                    error.setStandardButtons(QMessageBox.Ok)
                    error.exec_()
                    return
            except ZeroDivisionError:
                    self.plainTextEdit_kroc.clear()
                    self.plainTextEdit_znach.clear()
                    self.plainTextEdit_znachfun1.clear()
                    self.plainTextEdit_znachfun2.clear()
                    self.plainTextEdit_znachfun3.clear()
                    error = QMessageBox()
                    error.setWindowTitle("Помилка")
                    error.setText("Обчислення значень неможливе ")
                    error.setStandardButtons(QMessageBox.Ok)
                    error.exec_()
                    return
            self.label_resultvivid.setVisible(True)
            self.label_kroc.setVisible(False)
            self.label_znachx.setVisible(False)
            self.label_znacfun1.setVisible(False)
            self.label_znachfun2.setVisible(False)
            self.label_znachfun3.setVisible(False)
            self.label_znachfun.setVisible(False)
            self.pushButton_obchisliti1.setVisible(False)
            self.plainTextEdit_kroc.setVisible(False)
            self.plainTextEdit_znachfun1.setVisible(False)
            self.plainTextEdit_znachfun2.setVisible(False)
            self.plainTextEdit_znachfun3.setVisible(False)
            self.plainTextEdit_znach.setVisible(False)
            self.pushButton_exit.setVisible(True)
            self.pushButton_povtor.setVisible(True)
            self.label_resulttext.setVisible(True)
            self.plainTextEdit_kroc.clear()
            self.plainTextEdit_znach.clear()
            self.plainTextEdit_znachfun1.clear()
            self.plainTextEdit_znachfun2.clear()
            self.plainTextEdit_znachfun3.clear()
            res = round(res, 7)
            res=str(res)
            self.label_resultvivid.setText(res)

    def obchisliti1_2(self):
            import math
            try:
                    doc = QtGui.QTextDocument()
                    doc.setHtml(self.label_help.text())
                    text = doc.toPlainText()
                    pohidna_1 = sympy.diff(text)
                    pohidna_2 = sympy.diff(pohidna_1)
                    X = float(self.plainTextEdit_znach_2.toPlainText())
                    X = str(X)
                    pohidna_2 = str(pohidna_2)
                    if "cos" in pohidna_2:
                            pohidna_2 = pohidna_2.replace("cos", "math.cos")
                    if "sin" in pohidna_2:
                            pohidna_2 = pohidna_2.replace("sin", "math.sin")
                    if "log" in pohidna_2:
                            pohidna_2 = pohidna_2.replace("log", "math.log")
                    res = eval(pohidna_2.replace("x", X))
            except ValueError:
                    self.plainTextEdit_znach_2.clear()
                    self.label_kroc_4.setText('')
                    error = QMessageBox()
                    error.setWindowTitle("Помилка")
                    error.setText("Ви ввели дані некоректно,або функція занадто важка для обчислення")
                    error.setStandardButtons(QMessageBox.Ok)
                    error.exec_()
                    return
            except ZeroDivisionError:
                    self.plainTextEdit_znach_2.clear()
                    self.label_kroc_4.setText('')
                    error = QMessageBox()
                    error.setWindowTitle("Помилка")
                    error.setText("Обчислення значень неможливе ")
                    error.setStandardButtons(QMessageBox.Ok)
                    error.exec_()
                    return
            except TypeError :
                    self.plainTextEdit_znach_2.clear()
                    self.label_kroc_4.setText('')
                    error = QMessageBox()
                    error.setWindowTitle("Помилка")
                    error.setText("Програма не підтримує складних функцій")
                    error.setStandardButtons(QMessageBox.Ok)
                    error.exec_()
                    return

            self.label_resultvivid.setVisible(True)
            self.pushButton_exit.setVisible(True)
            self.pushButton_povtor.setVisible(True)
            self.label_resulttext.setVisible(True)
            self.pushButton_cal19.setVisible(False)
            self.pushButton_cal23.setVisible(False)
            self.pushButton_cal22.setVisible(False)
            self.pushButton_cal21.setVisible(False)
            self.pushButton_cal20.setVisible(False)
            self.pushButton_cal17.setVisible(False)
            self.pushButton_cal16.setVisible(False)
            self.pushButton_obchisliti1_3.setVisible(False)
            self.pushButton_cal15.setVisible(False)
            self.pushButton_cal14.setVisible(False)
            self.pushButton_cal13.setVisible(False)
            self.pushButton_cal11.setVisible(False)
            self.pushButton_cal10.setVisible(False)
            self.pushButton_cal9.setVisible(False)
            self.pushButton_cal8.setVisible(False)
            self.pushButton_cal7.setVisible(False)
            self.pushButton_cal5.setVisible(False)
            self.pushButton_cal4.setVisible(False)
            self.pushButton_cal3.setVisible(False)
            self.pushButton_cal2.setVisible(False)
            self.pushButton_cal1.setVisible(False)
            self.label_znachx_2.setVisible(False)
            self.plainTextEdit_znach_2.setVisible(False)
            self.label_kroc_3.setVisible(False)
            self.label_kroc_4.setVisible(False)
            self.pushButton_obchisliti1_2.setVisible(False)
            res=round(res,7)
            self.label_resultvivid.setText(str(res))
            self.plainTextEdit_znach_2.clear()
            self.label_kroc_4.setText('')



    def ex(self):
        sys.exit()

    def povtor(self):
            self.pushButton_2spos.setVisible(True)
            self.label_privet.setVisible(True)
            self.pushButton_1spos.setVisible(True)
            self.label_resultvivid.setVisible(False)
            self.pushButton_exit.setVisible(False)
            self.pushButton_povtor.setVisible(False)
            self.label_resulttext.setVisible(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
